### ISSUE TITLE
Support options through URL parameter

### ISSUE THREAD

**Issue by rarenal** [yngrdyn/decide4me#1]
### Feature request
Support a URL parameter for specifying the options, so when using the tool on a regular basis, the same options don't need to be added everytime.

### Use cases
- When specifying "options" through a URL parameter, the options are filled with the parameter values
- Support for multiple options in the URL parameter
- When a new option is added, the URL parameter is updated

**Comment by yngrdyn** [comment]
Most of the points in the request were already addressed. Only missing point:

- When a new option is added, the URL parameter is updated.

Which needs further discussion.
